# Generated by Django 5.1.7 on 2025-04-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_theme',
            field=models.CharField(default='기본 테마', max_length=50),
        ),
    ]
