# Generated by Django 5.1.7 on 2025-03-31 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임은 한글, 영어, 숫자만 사용할 수 있습니다.', regex='^[0-9a-zA-Z가-힣]+$')]),
        ),
    ]
