# Generated by Django 5.1.7 on 2025-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us',
            name='comment',
        ),
    ]
