# Generated by Django 5.1.7 on 2025-05-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_remove_us_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectedDailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.dailymessage')),
            ],
        ),
    ]
